version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    depends_on:
      - sqlite
  sqlite:
    image: nouchka/sqlite3:latest
    volumes:
      - ./data:/data
    command: tail -f /dev/null
